# Generated by Django 4.2.4 on 2023-08-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_posts_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
